
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SCIMSQLConn
{

using System;
    using System.Collections.Generic;
    
public partial class department
{

    public department()
    {

        this.dept_emp = new HashSet<dept_emp>();

        this.dept_manager = new HashSet<dept_manager>();

    }


    public string dept_no { get; set; }

    public string dept_name { get; set; }



    public virtual ICollection<dept_emp> dept_emp { get; set; }

    public virtual ICollection<dept_manager> dept_manager { get; set; }

}

}
