
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SCIMSQLConn
{

using System;
    using System.Collections.Generic;
    
public partial class employee
{

    public employee()
    {

        this.dept_emp = new HashSet<dept_emp>();

        this.dept_manager = new HashSet<dept_manager>();

        this.salaries = new HashSet<salary>();

        this.titles = new HashSet<title>();

    }


    public int emp_no { get; set; }

    public Nullable<System.DateTime> birth_date { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public string gender { get; set; }

    public Nullable<System.DateTime> hire_date { get; set; }

    public string username { get; set; }

    public string primary_email { get; set; }

    public bool active { get; set; }



    public virtual ICollection<dept_emp> dept_emp { get; set; }

    public virtual ICollection<dept_manager> dept_manager { get; set; }

    public virtual ICollection<salary> salaries { get; set; }

    public virtual ICollection<title> titles { get; set; }

}

}
